# Generated by Django 4.2.11 on 2026-03-09 02:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('29.00'), max_digits=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='tenants.tenant')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_referrals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referrals',
                'indexes': [models.Index(fields=['referrer', 'status'], name='referrals_referre_cefb5c_idx')],
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
