# Generated by Django 4.2.11 on 2026-03-01 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('ideas', 'Ideas'), ('archive', 'Archive')], default='personal', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'category'], name='notes_tenant__3e3ab1_idx'), models.Index(fields=['tenant', 'user', 'is_pinned'], name='notes_tenant__d062f8_idx')],
            },
        ),
    ]
