# Generated by Django 4.2.11 on 2026-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
