# Generated by Django 4.2.11 on 2026-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0006_landingtemplate_theme_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
