# Generated by Django 4.2.11 on 2026-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0008_portfoliosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
