# Generated by Django 4.2.11 on 2026-07-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0009_alter_portfoliosettings_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingtemplate',
            name='style_preset',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('soft', 'Soft')], default='modern', max_length=20),
        ),
    ]
