# Generated by Django 4.2.11 on 2026-07-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0011_alter_landingtemplate_style_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingtemplate',
            name='theme_colors',
            field=models.JSONField(blank=True, default=dict, help_text='{"hero_bg":"","hero_text":"","button_bg":"","nav_bg":"","nav_text":""}'),
        ),
    ]
