# Generated by Django 4.2.11 on 2026-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0012_alter_landingtemplate_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='hero_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"badge":"","ctaText":"","ctaUrl":"","showSocialLinks":false}'),
        ),
    ]
