# Generated by Django 4.2.11 on 2026-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0013_portfoliosettings_hero_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='contact_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"title":"","description":""}'),
        ),
    ]
