# Generated by Django 4.2.11 on 2026-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0015_portfoliosettings_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='skills_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"title":"","showSkills":false}'),
        ),
    ]
