# Generated by Django 4.2.11 on 2026-07-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0016_portfoliosettings_skills_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='services_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"title":"","items":[]}'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='testimonials_content',
            field=models.JSONField(blank=True, default=dict, help_text='{"title":"","items":[]}'),
        ),
    ]
