# Generated by Django 4.2.11 on 2026-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0017_portfoliosettings_services_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='style_preset',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('soft', 'Soft')], default='modern', max_length=20),
        ),
    ]
