# Generated by Django 4.2.11 on 2026-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0018_portfoliosettings_style_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='style_preset',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('soft', 'Soft'), ('editorial', 'Editorial'), ('bold', 'Bold')], default='modern', max_length=20),
        ),
    ]
