# Generated by Django 4.2.11 on 2026-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0019_alter_portfoliosettings_style_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='theme_colors',
            field=models.JSONField(blank=True, default=dict, help_text='{"background":"","sidebar_bg":""}'),
        ),
    ]
