# Generated by Django 4.2.11 on 2026-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0020_cvdocument_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='style_preset',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('soft', 'Soft')], default='modern', max_length=20),
        ),
    ]
