# Generated by Django 4.2.11 on 2026-07-03 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0021_cvdocument_style_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('landing', 'Landing'), ('portafolio', 'Portafolio'), ('cv', 'CV')], max_length=20)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('share', 'Share')], default='view', max_length=10)),
                ('session_hash', models.CharField(blank=True, max_length=32)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_events', to='digital_services.publicprofile')),
            ],
            options={
                'db_table': 'digital_page_events',
                'indexes': [models.Index(fields=['profile', 'service', 'event_type', 'created_at'], name='digital_pag_profile_b4856c_idx')],
            },
        ),
    ]
