# Generated by Django 4.2.11 on 2026-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0022_pageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='custom_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
