# Generated by Django 4.2.11 on 2026-07-23 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_services', '0023_digitalcard_custom_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('avatar', 'Avatar'), ('og_image', 'OG Image'), ('portfolio_cover', 'Portada de portafolio'), ('portfolio_gallery', 'Galería de portafolio'), ('cv_photo', 'Foto de CV'), ('landing_image', 'Imagen de landing')], max_length=20)),
                ('file', models.ImageField(upload_to='digital_assets/%Y/%m/')),
                ('size', models.PositiveIntegerField()),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='digital_services.publicprofile')),
            ],
            options={
                'db_table': 'digital_assets',
                'indexes': [models.Index(fields=['profile', 'slot'], name='digital_assets_prof_slot_idx')],
            },
        ),
    ]
