# Generated by Django 4.2.11 on 2026-03-01 06:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('python', 'Python'), ('bash', 'Bash'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('yaml', 'YAML'), ('dockerfile', 'Dockerfile'), ('go', 'Go'), ('rust', 'Rust'), ('java', 'Java'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snippets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'language'], name='snippets_tenant__e1f8cd_idx'), models.Index(fields=['tenant', 'user', 'created_at'], name='snippets_tenant__286330_idx')],
            },
        ),
    ]
