# Generated by Django 4.2.11 on 2026-07-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'ordering': ['-is_favorite', '-created_at']},
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['tenant', 'user', 'is_favorite'], name='snippets_tenant__ada2fc_idx'),
        ),
    ]
