# Generated by Django 4.2.11 on 2026-03-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantservice',
            new_name='tenant_serv_tenant__8737b3_idx',
            old_name='tenant_services_tenant_status_idx',
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
