# Generated by Django 4.2.11 on 2026-02-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial_tenant_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_slug_3181c2_idx',
            old_name='tenants_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_subdoma_69cf01_idx',
            old_name='tenants_subdomain_idx',
        ),
    ]
