# Generated by Django 4.2.11 on 2026-06-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/favicons/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
    ]
