# Generated by Django 4.2.11 on 2026-06-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_favicon_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='professional_trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
