# Generated by Django 4.2.11 on 2026-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_status_alter_yapeconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
