# Generated by Django 4.2.11 on 2026-07-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_plan_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_reminders_sent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='yapepaymentproof',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subs_period_end_idx'),
        ),
    ]
