"""
CurrencyConfig: saca el tipo de cambio de YapeConfig —donde quedó acoplado a un
método de pago— y lo convierte en configuración de plataforma.

La data migration copia el valor vigente para que ningún lector vea un número
distinto tras el despliegue: el día del deploy la tasa es exactamente la misma,
solo cambia de sitio.
"""
# Generated by Django 4.2.11 on 2026-07-26 03:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_rate_forward(apps, schema_editor):
    """YapeConfig.exchange_rate → CurrencyConfig.usd_to_pen (fila pk=1)."""
    YapeConfig = apps.get_model('subscriptions', 'YapeConfig')
    CurrencyConfig = apps.get_model('subscriptions', 'CurrencyConfig')

    yape = YapeConfig.objects.filter(pk=1).first()
    rate = Decimal(yape.exchange_rate) if yape else Decimal('3.75')

    CurrencyConfig.objects.update_or_create(
        pk=1,
        defaults={
            'usd_to_pen': rate.quantize(Decimal('0.0001')),
            'default_display_currency': 'USD',
            'source': 'manual',
        },
    )


def copy_rate_backward(apps, schema_editor):
    """Reverse best-effort: devuelve el valor a la columna vieja (2 decimales)."""
    YapeConfig = apps.get_model('subscriptions', 'YapeConfig')
    CurrencyConfig = apps.get_model('subscriptions', 'CurrencyConfig')

    cfg = CurrencyConfig.objects.filter(pk=1).first()
    if cfg is None:
        return
    YapeConfig.objects.update_or_create(
        pk=1,
        defaults={'exchange_rate': Decimal(cfg.usd_to_pen).quantize(Decimal('0.01'))},
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0009_subscription_grace_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_pen', models.DecimalField(decimal_places=4, default=Decimal('3.7500'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('default_display_currency', models.CharField(choices=[('USD', 'US Dollar'), ('PEN', 'Sol peruano')], default='USD', max_length=3)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], default='manual', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency_config',
            },
        ),
        migrations.RunPython(copy_rate_forward, copy_rate_backward),
    ]
