"""
Snapshot histórico del cobro en soles.

El cliente que paga por Yape transfiere SOLES, pero hasta ahora solo se persistía
el importe en USD y la tasa se consultaba siempre en vivo. Si la tasa se movía
entre el pago y la aprobación del comprobante, el importe del screenshot dejaba de
cuadrar con el panel sin forma de reconstruir por qué.

Las 4 columnas son NULLABLE y **sin backfill** a propósito: los comprobantes y
facturas ya existentes no tienen tasa registrada, y rellenarlos con la de hoy
sería fabricar un dato histórico indetectable. La UI muestra "sin conversión
registrada" en esos casos.

Nullable y sin default → en PostgreSQL es un ADD COLUMN instantáneo, sin
reescritura de tabla, aunque `invoices` crezca.
"""
# Generated by Django 4.2.11 on 2026-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_currencyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_pen_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='yapepaymentproof',
            name='amount_pen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='yapepaymentproof',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
