"""
El método de pago pasa a ser un dato: una fila de configuración por método en vez del
singleton de Yape, y un discriminador en el comprobante.

Aditiva por diseño. El `method` del comprobante nace con default 'yape', así que todo
lo existente queda clasificado sin tocar una sola fila, y la configuración de Yape se
copia a la tabla nueva para que los endpoints heredados —que el Hub en producción sigue
llamando— sirvan exactamente el mismo contrato.

La fila de PayPal se siembra **deshabilitada**: un método sin configurar no debe
ofrecerse, y mientras esté apagado los endpoints de creación rechazan comprobantes de
ese método. Eso es lo que impide que un recibo de PayPal llegue al workflow de n8n, cuyo
prompt de Vision está escrito para leer capturas de Yape.
"""
# Generated by Django 4.2.11 on 2026-07-27 02:36

from django.db import migrations, models


def seed_methods(apps, schema_editor):
    """Yape hereda su configuración actual; PayPal nace vacío y apagado."""
    YapeConfig = apps.get_model('subscriptions', 'YapeConfig')
    PaymentMethodConfig = apps.get_model('subscriptions', 'PaymentMethodConfig')

    yape = YapeConfig.objects.filter(pk=1).first()
    PaymentMethodConfig.objects.update_or_create(
        method='yape',
        defaults={
            'display_name':      'Yape',
            'is_enabled':        yape.is_enabled if yape else True,
            'sort_order':        10,
            'phone':             yape.phone if yape else '',
            'holder_name':       yape.holder_name if yape else '',
            'instructions_note': yape.instructions_note if yape else '',
        },
    )
    PaymentMethodConfig.objects.update_or_create(
        method='paypal',
        defaults={'display_name': 'PayPal', 'is_enabled': False, 'sort_order': 20},
    )


def unseed_methods(apps, schema_editor):
    apps.get_model('subscriptions', 'PaymentMethodConfig').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_payment_currency_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('yape', 'Yape'), ('paypal', 'PayPal')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('instructions_note', models.TextField(blank=True, default='')),
                ('holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_configs',
                'ordering': ['sort_order', 'method'],
            },
        ),
        migrations.AddField(
            model_name='yapepaymentproof',
            name='method',
            field=models.CharField(choices=[('yape', 'Yape'), ('paypal', 'PayPal')], default='yape', max_length=20),
        ),
        migrations.AddField(
            model_name='yapepaymentproof',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(seed_methods, unseed_methods),
    ]
