# Generated by Django 4.2.11 on 2026-03-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('certificate_pem', models.TextField(blank=True)),
                ('alert_30_sent', models.BooleanField(default=False)),
                ('alert_7_sent', models.BooleanField(default=False)),
                ('alert_1_sent', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssl_certs',
                'ordering': ['valid_until'],
                'indexes': [models.Index(fields=['tenant', 'user', 'domain'], name='ssl_certs_tenant__81263b_idx'), models.Index(fields=['tenant', 'valid_until'], name='ssl_certs_tenant__941976_idx')],
            },
        ),
    ]
