# Generated by Django 4.2.11 on 2026-07-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-is_favorite', '-created_at']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['tenant', 'user', 'is_favorite'], name='bookmarks_tenant__7bde35_idx'),
        ),
    ]
