# Generated by Django 4.2.11 on 2026-05-13 18:20

import apps.releases.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], max_length=10)),
                ('file', models.FileField(upload_to=apps.releases.models._release_upload_path)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('file_size', models.BigIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('release_notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('download_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'desktop_releases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_published'], name='release_platform_pub_idx'), models.Index(fields=['version', 'platform'], name='release_version_platform_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='desktoprelease',
            constraint=models.UniqueConstraint(fields=('version', 'platform'), name='unique_release_version_platform'),
        ),
    ]
