# Generated by Django 4.2.11 on 2026-02-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial_user_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_tenant__afadfd_idx',
            old_name='users_tenant_email_idx',
        ),
    ]
