# Generated by Django 4.2.11 on 2026-03-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production'), ('all', 'All Environments')], default='all', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_variables', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_variables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'env_variables',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['tenant', 'user', 'environment'], name='env_variabl_tenant__bac1e8_idx')],
                'unique_together': {('tenant', 'user', 'key', 'environment')},
            },
        ),
    ]
