# Generated by Django 4.2.11 on 2026-06-27 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_professional_trial_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salt', models.CharField(max_length=64)),
                ('wrapped_dek', models.TextField()),
                ('master_verifier', models.CharField(max_length=255)),
                ('recovery_salt', models.CharField(max_length=64)),
                ('wrapped_dek_recovery', models.TextField()),
                ('recovery_verifier', models.CharField(max_length=255)),
                ('recovery_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_keys', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_keys',
            },
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('login', 'Login'), ('api_key', 'API Key'), ('secure_note', 'Secure Note'), ('card', 'Card')], default='login', max_length=20)),
                ('data_ciphertext', models.TextField()),
                ('favorite', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_items',
                'ordering': ['-favorite', 'title'],
                'indexes': [models.Index(fields=['tenant', 'user', 'item_type'], name='vault_items_tenant__701c75_idx')],
            },
        ),
    ]
