# Generated by Django 4.2.11 on 2026-07-08 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_professional_trial_used'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultkey',
            name='public_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vaultkey',
            name='wrapped_private_key',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='VaultShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sealed_payload', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='vault.vaultitem')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_shares_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_shares_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_shares', to='tenants.tenant')),
            ],
            options={
                'db_table': 'vault_shares',
                'indexes': [models.Index(fields=['tenant', 'shared_with'], name='vault_share_tenant__ff8bdd_idx')],
                'unique_together': {('item', 'shared_with')},
            },
        ),
    ]
