# Generated by Django 4.2.11 on 2026-07-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultkey_public_key_vaultkey_wrapped_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultkey',
            name='wrapped_private_key_recovery',
            field=models.TextField(blank=True),
        ),
    ]
