# Generated by Django 4.2.11 on 2026-07-01 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('icon_color', models.CharField(blank=True, default='#6366f1', max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('link_url', models.URLField(blank=True)),
                ('badge_text', models.CharField(blank=True, max_length=30)),
                ('target_apps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
