# Generated by Django 4.2.11 on 2026-03-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ed25519', 'Ed25519'), ('ecdsa', 'ECDSA'), ('dsa', 'DSA')], default='rsa', max_length=20)),
                ('fingerprint', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ssh_keys',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'user', 'algorithm'], name='ssh_keys_tenant__a86020_idx')],
            },
        ),
    ]
