# Generated by Django 4.2.11 on 2026-03-01 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_rename_tenants_slug_idx_tenants_slug_3181c2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('can_read', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'share_permissions',
                'unique_together': {('permission_level', 'resource_type')},
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('project', 'Project'), ('section', 'Section'), ('item', 'Item')], max_length=50)),
                ('resource_id', models.UUIDField()),
                ('permission_level', models.CharField(choices=[('viewer', 'Viewer'), ('commenter', 'Commenter'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('is_inherited', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tenants.tenant')),
            ],
            options={
                'db_table': 'shares',
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='shares_tenant__c50236_idx'), models.Index(fields=['tenant', 'shared_with'], name='shares_tenant__760c2d_idx')],
                'unique_together': {('tenant', 'resource_type', 'resource_id', 'shared_with')},
            },
        ),
    ]
