# Generated by Django 4.2.11 on 2026-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='resource_type',
            field=models.CharField(choices=[('project', 'Project'), ('section', 'Section'), ('item', 'Item'), ('snippet', 'Snippet'), ('note', 'Note'), ('contact', 'Contact')], max_length=50),
        ),
    ]
