# Generated by Django 4.2.11 on 2026-04-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__27d8a8_idx',
            old_name='notif_tenant_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__c6d245_idx',
            old_name='notif_tenant_category_idx',
        ),
    ]
