# Generated by Django 4.2.11 on 2026-06-26 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_tenant_professional_trial_used'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='ChatConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_connections_received', to=settings.AUTH_USER_MODEL)),
                ('addressee_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_connections_as_addressee', to='tenants.tenant')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_connections_sent', to=settings.AUTH_USER_MODEL)),
                ('requester_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_connections_as_requester', to='tenants.tenant')),
            ],
            options={
                'db_table': 'chat_connections',
                'indexes': [models.Index(fields=['addressee', 'status'], name='chat_connec_address_3bdf5d_idx'), models.Index(fields=['requester', 'status'], name='chat_connec_request_d2908c_idx')],
                'unique_together': {('requester', 'addressee')},
            },
        ),
    ]
