# Generated by Django 4.2.11 on 2026-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatconnection_invited_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('self', 'Self')], default='direct', max_length=10),
        ),
    ]
